version: "2"
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "6001:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web

  data:
    image: daocloud.io/library/postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    ports:
      - "5001:5432"
